server:
  port: ${PORT:8082}
management:
  security:
    enabled: false
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    non-secure-port: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.uri:http://127.0.0.1:8761}/eureka/
spring:
  rabbitmq:
    host: ${cloudamqp.credentials.http_api_uri:localhost}
    port: 32774
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        mcdonalds:
          destination: mcdonalds
          binder: rabbit
    config:
      uri: ${vcap.services.config.credentials.uri:http://127.0.0.1:8888}
mcdonalds:
  order:
    chance: ${CHANCE:100}
