server:
  port: ${PORT:9999}
management:
  security:
    enabled: false
ribbon:
  isSecure: true
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    statusPageUrl: http://${eureka.instance.hostname}/application/info
    healthCheckUrl: http://${eureka.instance.hostname}/application/health
    homePageUrl: http://${eureka.instance.hostname}/
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port: 80
    non-secure-port-enabled: false
    secure-port-enabled: true
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.uri:http://127.0.0.1:8761}/eureka/