server:
  port: 8083
management:
  security:
    enabled: false
  context-path: /
spring:
  rabbitmq:
    host: localhost
    port: 32774
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        rick:
          destination: rick
          binder: rabbit
        meeseeks:
          destination: meeseeks
          binder: rabbit
        mcdonalds:
          destination: mcdonalds
          binder: rabbit
