server:
  port: 8083
management:
  security:
    enabled: false
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    non-secure-port: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.uri:http://127.0.0.1:8761}/eureka/
spring:
  rabbitmq:
    host: localhost
    port: 32774
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        rick:
          destination: rick
          binder: rabbit
        meeseeks:
          destination: meeseeks
          binder: rabbit
        mcdonalds:
          destination: mcdonalds
          binder: rabbit
