server:
  port: 8080
management:
  security:
    enabled: false
  context-path: /
spring:
  rabbitmq:
    host: localhost
    port: 32775
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        voice:
          destination: voice
          binder: rabbit