server:
  port: ${PORT:8081}
management:
  security:
    enabled: false
  cloudfoundry:
    enabled:
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    statusPageUrl: http://${eureka.instance.hostname}/application/info
    healthCheckUrl: http://${eureka.instance.hostname}/application/health
    homePageUrl: http://${eureka.instance.hostname}/
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.uri:http://127.0.0.1:8761}/eureka/
spring:
  rabbitmq:
    host: ${cloudamqp.credentials.http_api_uri:localhost}
    port: 32774
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        rick:
          destination: meeseeks
          binder: rabbit